# golangci-lint configuration v2
# https://golangci-lint.run/docs/configuration/
version: "2"

linters:
  default: standard
  enable:
    # Security
    - gosec        # Security issues
    - bodyclose    # HTTP response body close

    # Code quality
    - gocyclo      # Cyclomatic complexity
    - gocognit     # Cognitive complexity
    - goconst      # Repeated strings that could be constants
    - gocritic     # Comprehensive linting
    - misspell     # Common spelling mistakes
    - unconvert    # Unnecessary type conversions
    - unparam      # Unused function parameters
    - nakedret     # Naked returns in long functions
    - prealloc     # Slice preallocation
    - nolintlint   # Ill-formed //nolint directives

    # Error handling (∂S: boundary verification)
    - errorlint    # Error wrapping issues
    - nilerr       # Returning nil error when err != nil
    - nilnil       # Returning (nil, nil) hides errors
    - errchkjson   # JSON marshal/unmarshal error checking

    # Type safety (∂S: make invalid unrepresentable)
    - exhaustive   # Enum switch exhaustiveness
    - durationcheck # Duration multiplication errors
    - contextcheck # Context propagation across boundaries
    - forcetypeassert # Unchecked type assertions
    - musttag      # Required struct tags for marshaling
    - recvcheck    # Receiver type consistency

    # Anti-patterns (∂S: code smells, LLM pitfalls)
    - containedctx # Context stored in struct
    - fatcontext   # Nested context in loops
    - nestif       # Deeply nested if statements
    - dogsled      # Too many blank identifiers
    - noctx        # Missing context in HTTP/SQL calls
    - predeclared  # Shadowing predeclared identifiers

    # Architecture (∂S: separation of concerns)
    - dupl         # Code duplication detection
    - iface        # Interface pollution detection

    # Style
    - revive       # Fast, configurable linter
    - dupword      # Duplicate words in comments/strings

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # allow _ = to explicitly ignore errors
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println

    gocyclo:
      min-complexity: 25  # raised for complex validation funcs

    gocognit:
      min-complexity: 30

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam        # VZ types are large by design
        - unnamedResult    # Named results not always needed
        - paramTypeCombine # Style preference

    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck)
        - G204  # Subprocess with variable (we use exec.LookPath)
        - G301  # Dir permissions > 0750 (intentional for shared dirs)
        - G302  # File permissions > 0600 (intentional for log files)
        - G304  # File path from variable (we validate paths)
        - G306  # WriteFile permissions > 0600 (intentional for readable files)
        - G115  # Integer overflow (we check bounds)

    govet:
      enable-all: true
      disable:
        - shadow          # Too noisy
        - fieldalignment  # Optimization suggestions not worth churn

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    exhaustive:
      default-signifies-exhaustive: true  # switch default: case counts as exhaustive

    nestif:
      min-complexity: 5  # allow moderate nesting

    dupl:
      threshold: 150  # lines threshold for duplication

    iface:
      enable:
        - identical  # interfaces with identical methods
        - unused     # unused interface methods

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      # Test files can have longer functions and test-specific patterns
      - path: '_test\.go'
        linters:
          - gocyclo
          - gocognit
          - funlen
          - dupl          # Test cases often repeat patterns
          - nestif        # Test setup can be nested
          - forcetypeassert # Test assertions often type-assert
          - containedctx  # Test helpers may store context
          - errchkjson    # Test data often ignores errors
          - noctx         # Test helpers use simplified net calls

      # Main and command files often have setup code
      - path: cmd/
        linters:
          - gocognit

      # Allow log.Fatal in main
      - path: main\.go
        linters:
          - gocritic
        text: "exitAfterDefer"

      # Transport layer uses simplified net calls by design
      # TODO: consider adding context to Transport interface
      - path: 'internal/control/(transport|client)\.go'
        linters:
          - noctx

      # Internal VM operations are sync and don't need cancellation
      - path: 'internal/vm/(assets|forwarder)\.go'
        linters:
          - noctx

      # Util package name is intentional
      - path: 'internal/util/'
        linters:
          - revive
        text: "var-naming"

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
