#!/bin/bash
# Generate lint-compliant Homebrew formula for bladerunner
# Usage: ./scripts/generate-formula.sh <version>
#
# This script generates a formula that:
# - Downloads pre-built binaries from GitHub releases
# - Has def install at class level (passes homebrew lint)
# - Supports darwin on arm64/x86_64 only

set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 <version>" >&2
  exit 1
fi

# Strip leading 'v' if present
VERSION="${VERSION#v}"

REPO="stuffbucket/bladerunner"
RELEASE_URL="https://github.com/${REPO}/releases/download/v${VERSION}"

# Fetch checksums
CHECKSUMS_URL="${RELEASE_URL}/checksums.txt"
echo "Fetching checksums from ${CHECKSUMS_URL}..." >&2
CHECKSUMS=$(curl -sL "$CHECKSUMS_URL")

if [[ -z "$CHECKSUMS" ]]; then
  echo "Error: Could not fetch checksums" >&2
  exit 1
fi

# Extract SHA256 for Apple Silicon
sha=$(echo "$CHECKSUMS" | grep "bladerunner_${VERSION}_darwin_aarch64.tar.gz" | awk '{print $1}')
if [[ -z "$sha" ]]; then
  echo "Error: Could not find checksum for darwin_aarch64" >&2
  exit 1
fi
SHA_DARWIN_ARM64="$sha"

# Generate formula
cat <<EOF
# typed: strict
# frozen_string_literal: true

# This formula was auto-generated by scripts/generate-formula.sh
class Bladerunner < Formula
  desc "Standalone Incus VM runner for macOS using Apple Virtualization.framework"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  url "${RELEASE_URL}/bladerunner_${VERSION}_darwin_aarch64.tar.gz"
  sha256 "${SHA_DARWIN_ARM64}"

  depends_on :macos
  depends_on macos: :ventura
  depends_on arch: :arm64

  def install
    bin.install "br"
    # Install entitlements file to share directory for reference
    share.install "vz.entitlements"
  end

  def post_install
    # Codesign the binary with Virtualization entitlements after installation
    # Requires Xcode Command Line Tools (codesign utility)
    unless system "which", "codesign", [:out, :err] => File::NULL
      opoo "codesign not found - Xcode Command Line Tools may not be installed"
      opoo "Install with: xcode-select --install"
      opoo "Then re-sign the binary: codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br"
      return
    end

    # Sign the binary with Virtualization framework entitlements
    system "codesign", "--entitlements", "\#{share}/vz.entitlements", "-s", "-", "-f", "\#{bin}/br"
    
    # Verify the signature was applied
    unless system "codesign", "--verify", "\#{bin}/br", [:out, :err] => File::NULL
      opoo "Failed to verify codesign - the binary may not work correctly"
      opoo "You can manually re-sign with: codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br"
    end
  end

  def caveats
    <<~EOS
      bladerunner uses Apple's Virtualization framework.

      Requirements:
      - Apple Silicon Mac (M1/M2/M3/M4)
      - macOS 13+ (Ventura or later)
      - Xcode Command Line Tools (for codesigning)

      Intel Macs are not supported.

      If you don't have Xcode Command Line Tools installed:
        xcode-select --install

      The binary is automatically signed with Virtualization entitlements during
      installation. If you encounter permission issues, manually re-sign:
        codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br

      For bridged networking, additional entitlements may be needed.
      See: https://github.com/stuffbucket/bladerunner#bridged-networking
    EOS
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/br --version 2>&1")
  end
end
EOF
